title: IL POLIMATE
email: you@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Intelligence Strategica.
baseurl: "" # Lascia vuoto se il sito Ã¨ marcorzzn.github.io
url: "https://marcorzzn.github.io" 
twitter_username: marcorzzn
github_username:  marcorzzn

# IMPOSIZIONI TECNICHE
markdown: kramdown
theme: jekyll-theme-minimal
permalink: /:year/:month/:day/:title/
future: true
