title: IL POLIMATE
description: Intelligence Strategica.
author: marcorzzn
email: you@example.com

# URL CONFIGURATION
# Se la tua repo si chiama "The-Polymath-Brief", lascia cos√¨:
baseurl: "/The-Polymath-Brief" 
# Se l'hai rinominata "marcorzzn.github.io", metti: baseurl: ""

url: "https://marcorzzn.github.io"

# BUILD SETTINGS
markdown: kramdown
# theme: jekyll-theme-minimal  <-- COMMENTATO PER EVITARE CONFLITTI
permalink: /:year/:month/:day/:title.html
future: true
plugins:
  - jekyll-feed
